### PR TITLE
Rent model

### PR DESCRIPTION
**Pull request by NicolasLeutwyler**
# Summary

* Rent model added

# Trello Card
* [Card.](https://trello.com/c/COio66t5/22-crear-modelo-de-rent)

### CODE REVIEW

**Comment by mdesanti** [comment]
@NicolasLeutwyler no tests?

**Comment by NicolasLeutwyler** [comment]
@mdesanti no tests, the card says nothing about tests.

**Comment by mdesanti** [comment]
@NicolasLeutwyler the user can not access to all of his rents. You should be able to do `user.rents` and get a list of all of the user's rents

**Comment by NicolasLeutwyler** [comment]
I think it is done now

**Pull request merged**
